application: table-stacker
version: 1
runtime: python
api_version: 1

handlers:
- url: /remote_api 
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py 
  login: admin

- url: /_/.*
  script: tasks/main.py
  login: admin

- url: /media
  static_dir: media

- url: /csv
  static_dir: csv

- url: /.*
  script: main.py
